version: '3.9'

services:
  web:
    build: .
    container_name: merch_web
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: example
      DB_NAME: merch_store
      STORE_NAME: MerchHub
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: merch_db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: merch_store
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/merch_store.sql:/docker-entrypoint-initdb.d/01_merch_store.sql:ro

  phpmyadmin:
    image: phpmyadmin:5
    container_name: merch_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: example
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
